/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AxesSettings: typeof import('./src/components/Settings/AxesSettings.vue')['default']
    CanvasAxes: typeof import('./src/components/Canvas/CanvasAxes.vue')['default']
    CanvasAxesGuide: typeof import('./src/components/Canvas/CanvasAxesGuide.vue')['default']
    CanvasAxis: typeof import('./src/components/Canvas/CanvasAxis.vue')['default']
    CanvasCursor: typeof import('./src/components/Canvas/CanvasCursor.vue')['default']
    CanvasFooter: typeof import('./src/components/Canvas/CanvasFooter.vue')['default']
    CanvasHeader: typeof import('./src/components/Canvas/CanvasHeader.vue')['default']
    CanvasMain: typeof import('./src/components/Canvas/CanvasMain.vue')['default']
    CanvasPlot: typeof import('./src/components/Canvas/CanvasPlot.vue')['default']
    CanvasPlots: typeof import('./src/components/Canvas/CanvasPlots.vue')['default']
    ColorSettings: typeof import('./src/components/Settings/ColorSettings.vue')['default']
    DatasetManager: typeof import('./src/components/DatasetManager/DatasetManager.vue')['default']
    DataTable: typeof import('./src/components/Export/DataTable.vue')['default']
    ExtractorSettings: typeof import('./src/components/Settings/ExtractorSettings.vue')['default']
    ImageSettings: typeof import('./src/components/Settings/ImageSettings.vue')['default']
    LineExtractSettings: typeof import('./src/components/Settings/LineExtractSettings.vue')['default']
    MagnifierAxes: typeof import('./src/components/Magnifier/MagnifierAxes.vue')['default']
    MagnifierAxis: typeof import('./src/components/Magnifier/MagnifierAxis.vue')['default']
    MagnifierAxisLabelX: typeof import('./src/components/Magnifier/MagnifierAxisLabelX.vue')['default']
    MagnifierAxisLabelY: typeof import('./src/components/Magnifier/MagnifierAxisLabelY.vue')['default']
    MagnifierExtractSize: typeof import('./src/components/Magnifier/MagnifierExtractSize.vue')['default']
    MagnifierHorizontalLine: typeof import('./src/components/Magnifier/MagnifierHorizontalLine.vue')['default']
    MagnifierImage: typeof import('./src/components/Magnifier/MagnifierImage.vue')['default']
    MagnifierMain: typeof import('./src/components/Magnifier/MagnifierMain.vue')['default']
    MagnifierPlots: typeof import('./src/components/Magnifier/MagnifierPlots.vue')['default']
    MagnifierSettings: typeof import('./src/components/Magnifier/MagnifierSettings.vue')['default']
    MagnifierSettingsBtn: typeof import('./src/components/Magnifier/MagnifierSettingsBtn.vue')['default']
    MagnifierVerticalLine: typeof import('./src/components/Magnifier/MagnifierVerticalLine.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    MaskSettings: typeof import('./src/components/Settings/MaskSettings.vue')['default']
    PlotsTable: typeof import('./src/components/Export/PlotsTable.vue')['default']
    SymbolExtractSettings: typeof import('./src/components/Settings/SymbolExtractSettings.vue')['default']
  }
}
